# Generated by Django 4.1.3 on 2022-11-27 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servigou', '0002_alter_user_celular_alter_user_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='ruta',
        ),
        migrations.CreateModel(
            name='ServicioRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servigou.ruta')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servigou.servicio')),
            ],
        ),
    ]
