# Generated by Django 4.1.3 on 2022-11-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servigou', '0004_rol_usuariorol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariorol',
            name='fecha_registro',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
