# Generated by Django 4.1.3 on 2022-11-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servigou', '0005_usuariorol_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariorol',
            name='fecha_registro',
            field=models.DateTimeField(),
        ),
    ]
