# Generated by Django 4.1.3 on 2022-11-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servigou', '0007_remove_usuariorol_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariorol',
            name='fecha_registro',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
    ]
