# Generated by Django 4.1.3 on 2022-11-28 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servigou', '0010_alter_usuariorol_fecha_registro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioRol',
        ),
    ]
