# Generated by Django 4.1.3 on 2023-03-09 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servigou', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
