# Generated by Django 4.1.3 on 2023-03-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servigou', '0002_alter_servicio_fecha_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='cantidad_dinero',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
    ]
