# Generated by Django 4.1.3 on 2023-03-09 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servigou', '0003_servicio_cantidad_dinero_alter_servicio_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='estado_servicio',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='tipo',
        ),
    ]
