# Generated by Django 4.1.3 on 2023-03-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servigou', '0004_remove_servicio_estado_servicio_remove_servicio_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='cantidad_dinero',
            new_name='celular',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='entidad_pago',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='establecimiento',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='referencia_pago',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='supermercado',
        ),
        migrations.AddField(
            model_name='servicio',
            name='direccion',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
