# Generated by Django 4.1.3 on 2023-03-09 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servigou', '0007_pedimos_mercado_factura_encomienda_cajero'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Encomienda',
            new_name='Mensajeria',
        ),
    ]
