# Generated by Django 4.1.3 on 2023-03-09 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servigou', '0008_rename_encomienda_mensajeria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cajero',
            old_name='Servicio',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='Servicio',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='mensajeria',
            old_name='Servicio',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='mercado',
            old_name='Servicio',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='pedimos',
            old_name='Servicio',
            new_name='User',
        ),
    ]
