# Generated by Django 4.1.3 on 2023-03-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servigou', '0009_rename_servicio_cajero_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='User',
        ),
        migrations.RemoveField(
            model_name='mensajeria',
            name='User',
        ),
        migrations.RemoveField(
            model_name='mercado',
            name='User',
        ),
        migrations.RemoveField(
            model_name='pedimos',
            name='User',
        ),
        migrations.AddField(
            model_name='servicio',
            name='descripcion',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cajero',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
        migrations.DeleteModel(
            name='Mensajeria',
        ),
        migrations.DeleteModel(
            name='Mercado',
        ),
        migrations.DeleteModel(
            name='Pedimos',
        ),
    ]
