# Generated by Django 4.1.3 on 2023-03-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servigou', '0010_remove_factura_user_remove_mensajeria_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='tipo',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
