# Generated by Django 4.1.3 on 2023-03-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servigou', '0012_pqrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='estado',
            field=models.CharField(default='sin_asignar', max_length=50),
        ),
    ]
