# Generated by Django 4.1.3 on 2023-03-13 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servigou', '0014_pqrs_asunto_pqrs_email_pqrs_mensaje_pqrs_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pqrs',
            name='User',
        ),
    ]
