# Generated by Django 4.1.7 on 2023-04-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servigou', '0017_alter_servicio_repartidor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruta',
            old_name='valor_km',
            new_name='valor',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='incremento',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='km',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='porcentaje_liquidacion',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='total_liquidacion',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='transporte',
        ),
        migrations.AddField(
            model_name='ruta',
            name='nombre',
            field=models.CharField(default='ruta', max_length=30),
        ),
    ]
