# Generated by Django 4.1.7 on 2023-04-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servigou', '0018_rename_valor_km_ruta_valor_remove_ruta_incremento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='descripcion',
            field=models.CharField(default='ruta', max_length=100),
        ),
    ]
