# Generated by Django 4.1.3 on 2023-05-03 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servigou', '0029_alter_user_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='ruta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ruta', to='servigou.ruta'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='celular',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
