# Generated by Django 4.1.3 on 2023-05-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servigou', '0030_servicio_ruta_alter_servicio_celular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='sector',
        ),
    ]
