# Generated by Django 4.1.3 on 2023-06-06 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servigou', '0031_remove_servicio_sector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='Repartidor',
            new_name='repartidor',
        ),
    ]
